server:
  port: 8087
spring:
  application:
    name: auth-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
leyou:
  jwt:
    secret: leyou@Login(Auth}*^31)&heiMa% # 登录校验的密钥
    pubKeyPath: D:\\IDEA\\workspaces\\乐优商城\\code\\rsa\\rsa.pub # 公钥地址
    priKeyPath: D:\\IDEA\\workspaces\\乐优商城\\code\\rsa\\rsa.pri # 私钥地址
    expire: 1800 # 过期时间,单位分钟
    cookieName: LY_TOKEN
feign:
  hystrix:
    enabled: true
